### ISSUE TITLE
FEATURE REQUEST: Visualizer

### ISSUE THREAD

**Issue by Galvarino** [rowak/nanoleaf-desktop#18]
The visualizer for Spotify is really cool, but could this be expanded upon/simplified such that it visualizes whatever audio is playing on your computer? Would love to not have to connect an aux to my aurora and deal with the cable noise that creates ;-;

**Comment by rowak** [comment]
This is something that I have actually looked into when I first created the Spotify visualizer, and I am very much in agreement with you. After looking into this a bit, I concluded that it isn't really possible to route audio from other applications using the language that NFD is written in (Java). Especially not in a way that supports Windows, Mac, and Linux (one of the main goals of NFD). For this reason, I will say that this feature will not be added to NFD. _However,_ this is still an idea that I am very much interested in. It is likely that in the future I will look into trying to achieve this by remaking the somewhat broken Spotify visualizer as a better program that is separate from NFD. It's gonna take a while for me to get around to working on this though.

**Bonus/offtopic:** I almost forgot about this, but I threw together a really janky demo a long time ago that reacts to the audio playing on your computer using @bharat's "Haller" aurora audio visualizer. It relies on the user to configure their Windows audio settings to create a "loopback" (send audio output to input), but the end result is well worth it. Check out the fifth comment on [this thread](https://forum.nanoleaf.me/forum/community-support/razer-chroma-integration-not-working) for a step-by-step setup if you want to check it out.
