### ISSUE TITLE
spotify visualizer is broken (shows no song playing)

### ISSUE THREAD

**Issue by SammyMasala** [rowak/nanoleaf-desktop#19]
Per title. Completed the authentication process and still displays 'no song playing' after waiting 20+ minutes

**Comment by rowak** [comment]
I had this issue myself happen a few times when listening through Spotify on my phone. Try closing and reopening the Spotify app on your device first, then start playing music *before* you open Nanoleaf for Desktop and see if it recognizes the song playing. You shouldn't have to do this every time, I find it just happens sometimes for me (and I believe it is a problem on Spotify's end).

If this doesn't work, then I'll need you to post your log so I can figure out what is going on. You can see the log by running Nanoleaf for Desktop through the terminal/command prompt. The command for this is <code>java -jar nanoleaf-desktop.jar</code>. Note that nanoleaf-desktop.jar should be the absolute path to your app executable file (it doesn't have to be called that though). The log will record any errors in the terminal as they happen.

**Comment by SammyMasala** [comment]
The suggested fix worked. Thanks!
