### ISSUE TITLE
Fullscreen support issues with Ambient Lighting

### ISSUE THREAD

**Issue by Galvarino** [rowak/nanoleaf-desktop#2]
With certain applications, the panels don't sync up with fullscreen mode. Instead, they continue to read colors from the desktop. This occurred with only a few of my games, such as minecraft and freespace 2 (running from knossos). I tried to get around this with Magic Borderless, but only to receive a weirder response from the panels I don't see being relevant. This is a strange issue and I don't expect a full fix to be possible, especially considering it could likely be the fault of other applications. If needed, I can list other games I encountered this issue with, but those two are the only ones so far.

**Comment by rowak** [comment]
You're right, this issue might be out of my control according to [this thread on stackoverflow](https://stackoverflow.com/questions/12251376/taking-screenshot-in-java-robot-code-working-but-not-with-external-full-screen). Still, I'll try out minecraft on my end and see if this happens for me as well. In the meantime, would you mind trying to take a screenshot in fullscreen/magic borderless using snipping tool or printscreen, then let me know if the game content is being shown in the pic. Thanks!

**Comment by Galvarino** [comment]
Good idea! I did a large number of tests to discern what exactly was going on. I took a screenshot with both the snipping tool and printscreen with and without the borderless function. Without the borderless function, both attempts at taking a screenshot only show the desktop behind, no sign of the game window, as expected. With the borderless finction, it shows the game's pause menu even though the game was not paused when the screenshot was taken, and sometimes the image was glitched, where two small windows on the pause menu are visible. The important thing to note was that the pause menu was showing the moment the border window was activated (which was a pause menu of an area I was no longer in) which solves the mystery of the panels not changing, as they were simply referring to that backed up image. Borderless aside, it would seem that because the print screen function cannot see the window, this is not possible. I do note that my phillips hue sync setup DOES record the screen properly, but I have no idea how and don't expect you to know either. Thanks for the help, and I hope you can decipher something from these results.

**Comment by Galvarino** [comment]
My bad, didn't mean to close the issue.

**Comment by Galvarino** [comment]
Update, I managed to get it to work, sort of. If I use magic borderless's option to include the taskbar, and make the taskbar super small, it works as it should. I wonder if the window, when fully applied defines itself as something else no matter the case? And I wonder if there's a simpler way to work around that...

**Comment by rowak** [comment]
I just tried running the ambilight in fullscreen for both minecraft bedrock (windows 10) edition and the java edition. The java edition didn't work, but the bedrock edition actually worked perfectly. I'm not sure how you actually managed to take a screenshot in fullscreen, but my mouse seemed to be locked to the size of my main monitor so I wasn't able to see if the screenshots showed the game content. What game were you testing when you found that borderless fix?

I'll look into this problem a bit more over the next few days, but I'm not sure I'll be able to find a viable fix. I'll also see if fullscreen on MacOS has this problem as well.

**Comment by Galvarino** [comment]
I was testing minecraft java, and the way I did the screenshots was to use win+print screen and observe the screenshot later, and for snipping tool by using the timing function to quickly enter the window and take the snip. I use the two often. I'm not sure if I can be of much use from this point on; ever since checking with those two applications all other are working flawlessly (and beautifully). I'll let you know if I can find any information on why these fullscreen windows aren't present over the desktop space but others are... I've been asking around and googling but nothing so far. Thank you for your efforts!

**Comment by rowak** [comment]
Huh, that's a cool trick for screenshots I never thought of that! So are your games working perfectly in fullscreen now or in borderless?

**Comment by Galvarino** [comment]
They work, but now there's a small taskbar on the bottom of the screen since I have to keep it sort of out of fullscreen. I ran a quick experiment to make sure the region of the screen is the same in fullscreen, aka it's still over the desktop by using the set area function in the app. I would load a game, and while loading click the set area button. Then, when the game loaded and became fullscreen, I set the area of the screen over the fullscreen window (Which was already the same as it was for previous things) So the problem doesn't lie in the window existing elsewhere. I now think I have some understanding of the problem. Because a fullscreen window is described as having priority over all other elements on display, it could be possible that your program isn't using enough priority to be able to read this instance. It's probably not as though there's just a priority value somewhere you can edit, but at least this concept might make sense and could potentially be part of your current program. In terms of program authority, aka your program being under prioritized in the sense that it was less important to the computer (not the display) I ran the program in administrator mode to see if it would work. It didn't, meaning that the most likely cause of this issue is that whatever you are using to read the screen doesn't have enough of a priority to reach the full screen scale for some apps. I hope this is helpful to you in resolving the problem, and I wish you luck!

**Comment by rowak** [comment]
It looks like you've solved it! I tested this out with minecraft once again, and the lights didn't seem to update until the nanoleaf desktop app gained focus. Of course, this is a problem since the game itself requires focus for it to be playable, but I'll see if I can find a workaround. Thanks for all your help!

**Comment by rowak** [comment]
After looking into this a bit more, I have decided that I can't fix this issue. Unfortunately there isn't any sort of priority value that I can change to give my program access to higher level processes (although it was a good idea). The options for capturing the screen are limited, especially when my program is supposed to work cross-platform. Using the printscreen fix mentioned at the link in my first post seemed to work in borderless, but simply wouldn't work with fullscreen. The printscreen fix, however, required using a much slower method to capture the screen which in my opinion is not worth the trade off. I believe this is would be a similar situation for the steam F12 screenshot fix as well.

*For anyone finding this thread,* I recommend trying Galvarino's fix above.
