### ISSUE TITLE
Spotify Not Working

### ISSUE THREAD

**Issue by heezus** [rowak/nanoleaf-desktop#27]
Spotify integration does not show any songs playing. Possible they have updated their API. Only says "No Song Playing",

**Comment by heezus** [comment]
I tried doing the suggestion here: https://github.com/rowak/nanoleaf-desktop/issues/19 but had no luck

**Comment by rowak** [comment]
Your right, there is something strange going on here. In my case the spotify visualizer works correctly 90% of the time when I press the "enable" button. Did you try multiple times? If so, were you able to get it working at least once? (also note that if you open and close the app too many times in a short amount of time, your nanoleaf device may throttle or lock your connection for a few minutes)

Running the app in a terminal shows that the JSON response from spotify isn't being parsed correctly, and looking and the request itself shows that a 503 response is being returned with no data. According to the spotify web api documentation, a 503 response means:

> Service Unavailable - The server is currently unable to handle the request due to a temporary condition which will be alleviated after some delay. You can choose to resend the request again.

Based on this error code, I'm assuming that this is related to some internal spotify problem. If this is the case then we just have to wait for it to be fixed. Bump in a few days (just to remind me) if the issue still isn't fixed.

I also just wanted to mention that after typing this out, the problem seems to have gone away for me. I was a bit late in getting back to you (sorry) so maybe the problem was worse three hours ago. Let me know if you still have the problem.

**Comment by heezus** [comment]
Not sure if its relevant but I'm using Nanoleaf Shapes (triangle and mini triangle) and not seeing a preview. Says device is not supported. Here's the terminal output when I open the app and then try to load spotify.

`C:\Users\jrhow>java -jar C:\Users\jrhow\Downloads\Nanoleaf.for.Desktop.v0.8.6.jar                                       Dec 17, 2020 10:59:54 PM org.jnativehook.GlobalScreen getAutoRepeatRate                                                 INFO: hook_get_auto_repeat_rate [135]: SPI_GETKEYBOARDSPEED: 31.                                                                                                                                                                                Dec 17, 2020 10:59:54 PM org.jnativehook.GlobalScreen getAutoRepeatDelay                                                INFO: hook_get_auto_repeat_delay [149]: SPI_GETKEYBOARDDELAY: 1.                                                                                                                                                                                Dec 17, 2020 10:59:54 PM org.jnativehook.GlobalScreen getMultiClickIterval                                              INFO: hook_get_multi_click_time [208]: GetDoubleClickTime: 500.                                                                                                                                                                                 Dec 17, 2020 10:59:54 PM org.jnativehook.GlobalScreen getPointerSensitivity                                             INFO: hook_get_pointer_sensitivity [194]: SPI_GETMOUSESPEED: 10.                                                                                                                                                                                Dec 17, 2020 10:59:54 PM org.jnativehook.GlobalScreen getPointerAccelerationMultiplier                                  INFO: hook_get_pointer_acceleration_multiplier [163]: SPI_GETMOUSE[2]: 1.                                                                                                                                                                       Dec 17, 2020 10:59:54 PM org.jnativehook.GlobalScreen getPointerAccelerationThreshold                                   INFO: hook_get_pointer_acceleration_threshold [177]: SPI_GETMOUSE[0]: 6.                                                                                                                                                                        Dec 17, 2020 10:59:54 PM org.jnativehook.GlobalScreen getPointerAccelerationThreshold                                   INFO: hook_get_pointer_acceleration_threshold [179]: SPI_GETMOUSE[1]: 10.                                                                                                                                                                       java.lang.NullPointerException                                                                                                  at io.github.rowak.nanoleafdesktop.spotify.SpotifyPlayer.enableExternalStreaming(SpotifyPlayer.java:380)                at io.github.rowak.nanoleafdesktop.spotify.SpotifyPlayer.<init>(SpotifyPlayer.java:91)                                  at io.github.rowak.nanoleafdesktop.ui.panel.SpotifyPanel.trySetupPlayer(SpotifyPanel.java:348)                          at io.github.rowak.nanoleafdesktop.ui.panel.SpotifyPanel.lambda$1(SpotifyPanel.java:327)                                at java.lang.Thread.run(Unknown Source)   `

**Comment by heezus** [comment]
I have problems enabling Ambient lighting as well.

**Comment by rowak** [comment]
Ah I see haha I probably should have asked that first, my bad. Nanoleaf shapes actually **aren't supported** by the app currently (only the Aurora and Canvas are supported). The app doesn't lock you out if it detects unsupported hardware, so you may notice that some features work and others don't. I am hoping to add support for the shapes in the future, but I don't have the hardware right now to test on.

Besides the shapes, do you have an Aurora or Canvas device? If so, are you having these problems with them as well?

**Comment by heezus** [comment]
No worries. I only have shapes at the moment as this was a very recent
purchase. I'll check back often to see if you push any new releases to
support them in the future.
