### ISSUE TITLE
nanoleaf-api 0.1.2 unavailable

### ISSUE THREAD

**Issue by thenoname** [rowak/nanoleaf-desktop#31]
The currently published version of nanoleaf-api is 0.1.1, not 0.1.2. This means that the source cannot be compiled. Even with the source for nanoleaf-api, it cannot find 0.1.2 because the latest commit is still 0.1.1

**Comment by rowak** [comment]
You're right, sorry. I meant to do this when I released 0.9.0, but I rushed the release a bit and was tweaking a few things at the last minute and forgot about it. I'll release 0.1.2 of the api later tonight.

**Comment by thenoname** [comment]
> You're right, sorry. I meant to do this when I released 0.9.0, but I rushed the release a bit and was tweaking a few things at the last minute and forgot about it. I'll release 0.1.2 of the api later tonight.

Thanks :-)

**Comment by rowak** [comment]
Okay, changes are pushed to GitHub and Maven Central. You should be able to compile normally with maven in a few minutes.

**Comment by thenoname** [comment]
Thanks!
