### ISSUE TITLE
Palette selection doesn't allow manual input.

### ISSUE THREAD

**Issue by jaxcksn** [rowak/nanoleaf-desktop#4]
The palette selection UI doesn't allow for you to manually input RGB, HSB, or HEX values. You can only choose colors using the color wheel.

**Comment by rowak** [comment]
Thanks for sharing this! This problem should now be fixed in v0.7.2, however it won't be released for a few weeks. Would you mind verifying by testing [this build](https://ufile.io/i5z3s3ey)?

**Comment by jaxcksn** [comment]
Just tested the build, and can verify the bug is no longer present.

**Comment by rowak** [comment]
Great, thanks!
