### ISSUE TITLE
8.1 Rotation still broken and question about dynamic selection

### ISSUE THREAD

**Issue by Galvarino** [rowak/nanoleaf-desktop#5]
I'm assuming you noticed but the rotation for the latest version still doesn't work despite the fix. Question concerning rotation, does the orientation of the panels on the app affect the match of colors on screen when using selection mode on dynamic?

**Comment by rowak** [comment]
I actually wasn't aware that rotation is still broken on 0.8.1. Would you mind sharing a screenshot of what this looks like for you? Is it similar [to this?](https://i.imgur.com/59nIWOu.png)
To answer your question, yes and no, it doesn't directly *affect* selection mode however it is synced with selection mode. The layout you see in the preview should match both the physical layout and the layout being used for selection mode. Before v0.8.0 you were also able to rotate the panels in the preview window, however this would not have any affect on the layout used for selection mode.

**Comment by rowak** [comment]
Would you mind checking if you are still having this problem on the latest version [0.8.2](https://github.com/rowak/nanoleaf-desktop/releases/tag/v0.8.2)?

**Comment by Galvarino** [comment]
My bad for not replying for so long, last week of school, regents tests and such. The problem no longer occurs, and I enjoy the new snapping while rotating. Thank you!
